
name: build_and_test_plugin
on: push

jobs:
  job-name:
    runs-on: ubuntu-latest

    services:
      ceph:
        image: ceph/daemon:latest
        env:
          CEPH_DEMO_UID: demo_uid
          NETWORK_AUTO_DETECT: 4
        volumes:
           - ceph-data:/etc/ceph/ 

    container: 
      image: cephdovecot/travis-build-master-2.3:latest  
      options: "--entrypoint /bin/bash"    
      volumes:
        - ceph-data:/etc/ceph/
        - ${{ github.workspace }}/:/repo
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}          
      - name: run build
        run: /repo/.github/scripts/build_script.sh      
      - name: run tests
        run: ls ./        
