
name: build_and_test_plugin
on: push

jobs:
  job-name:
    runs-on: ubuntu-latest
  
    services:
      ceph:
        image: ceph/daemon:latest
        env:
          CEPH_DEMO_UID: demo_uid
          NETWORK_AUTO_DETECT: 4
        volumes:
           - ceph-data:/etc/ceph/ 

    container: 
      image: cephdovecot/travis-build-master-2.3:latest  
      options: "--entrypoint /bin/bash"    
      env:
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
      volumes:
        - ceph-data:/etc/ceph/
        - ${{ github.workspace }}/:/repo
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          submodules: true
          ref: ${{ github.ref }}
        working-directory: /repo
      - name: list all files
        run: ls -lah /repo
      - name: run build
        run: /repo/.github/scripts/build_script.sh    
      - name: run unit tests
        run: /repo/.github/scripts/run_unit_tests.sh  
      - name: run integration tests
        run: /repo/.github/scripts/run_tests.sh      
