
name: build_and_test_plugin
on: push

jobs:
  job-name:
    runs-on: ubuntu-latest

    services:
      ceph:
        image: ceph/daemon:latest
        env:
           - CEPH_DEMO_UID: demo_uid
           - NETWORK_AUTO_DETECT: 4
        volumes:
           - ceph-data:/etc/ceph/ 

    container: 
      image: cephdovecot/travis-build-master-2.3:latest      
      volumes:
        - ceph-data:/etc/ceph/
        - ./:/repo
    steps:
      - name: run build
        run: ./github/scripts/run-build.sh        
        shell: bash
      - name: run tests
        run: ./github/scripts/run-tests.sh
        shell: bash
